services:
  db:
    image: postgis/postgis:16-3.5-alpine
    container_name: postgres-postgis
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net: